BACKGROUND_PROMPTS = {
    "lei" : """
    A realistic ancient mountain valley scene grounded in early Chinese mythology, specifically inspired by the description of Cui Mountain from The Classic of Mountains and Seas (Shan Hai Jing).

The environment depicts a desolate yet believable mountain valley: rugged stone terrain, uneven ground, and a natural sense of age and abandonment. The mountains are covered with palm trees and nanmu trees, while the lower areas contain dense bamboo-like vegetation. The valley subtly reflects a contrast between sunlit and shaded slopes, suggesting mineral richness such as gold and jade in the brighter areas, and a colder, shadowed atmosphere in the darker regions. The overall color palette is muted and earthy, with a bleak, lonely, and slightly mysterious mood. Soft overcast lighting and faint mist enhance the sense of quiet tension.

In the center of the image stands a single human figure, shown full body from head to toe, clearly visible and fully within the frame. The figure is of moderate, natural size relative to the environment — not tiny, not dominant — standing firmly on the ground with both feet clearly touching the earth. The human faces directly toward the camera in a frontal view, standing still and composed. No other human figures appear anywhere in the scene.

Behind the human, positioned in the right rear area of the scene and hovering in the air, is a mythical beast described in Shan Hai Jing:
A bird known as Léi (鸓), resembling a magpie in shape, with red and black feathers, **two heads**, and **four legs**. The creature appears ancient and uncanny rather than frightening, with a strange, otherworldly presence that feels naturally embedded in this mythological landscape. It is captured mid-motion, subtly leaning forward as if preparing to descend toward the human, creating tension without overt violence or horror. The creature’s form should reflect its legendary ability to withstand fire, expressed through its texture, posture, or aura rather than explicit flames.

The composition emphasizes narrative balance and realism: the grounded human figure, the looming beast behind and above on the right, and the vast, empty mountain valley surrounding them. The visual style should be cinematic and realistic, avoiding cartoon, anime, or exaggerated fantasy illustration styles, with consistent lighting, natural textures, and a strong sense of physical space.
    """,
    "gu" : """
    A realistic ancient mountain valley scene grounded in early Chinese mythology, specifically inspired by the description of Zhong Mountain from The Classic of Mountains and Seas (Shan Hai Jing).

The environment depicts a barren and solemn mountain region: steep rocky cliffs, fractured stone ground, and an overwhelming sense of ancient desolation. Vegetation is sparse and withered, with only scattered hardy shrubs and dark, drought-resistant trees clinging to the slopes. The land appears dry and exhausted, with cracked earth in lower areas, subtly implying a prolonged drought. Distant mountain layers fade into pale mist and ash-colored clouds. The overall color palette is muted and restrained, dominated by off-white stone, dark gray rock, and subdued red-brown tones. Soft, diffused lighting and suspended dust in the air create a quiet but oppressive atmosphere, suggesting divine punishment rather than natural decay.

In the center of the image stands a single human figure, shown full body from head to toe, clearly visible and fully within the frame. The figure is of moderate, natural size relative to the environment — not tiny, not dominant — standing firmly on the ground with both feet clearly touching the earth. The human faces directly toward the camera in a frontal view, standing still and composed. No other human figures appear anywhere in the scene.

Behind the human, positioned in the right rear area of the scene and hovering in the air, is a mythical beast described in Shan Hai Jing:
A legendary being known as Gu (鼓). Its form combines human and draconic traits: a distinctly human-like face with an ancient, emotionless expression, set upon an elongated dragon body covered in dark, weathered scales. The creature bears avian characteristics — powerful talons and scorched black-and-red feathers emerging along its back and limbs — hinting at its later transformation into a bird of drought. Gu appears suspended in midair, neither attacking nor retreating, its presence heavy and inevitable. The creature does not appear overtly monstrous or violent, but radiates a calm, punitive divinity, as if acting as an instrument of cosmic retribution. Its existence alone suggests catastrophe: drought, desolation, and the withdrawal of heavenly favor.

The composition emphasizes narrative balance and grounded realism: the solitary human firmly anchored to the earth, the hovering divine beast behind and above on the right, and the vast, empty mountain landscape enveloping both figures. The visual style should be cinematic and realistic, avoiding cartoon, anime, or exaggerated fantasy illustration styles. Lighting remains consistent and natural, textures are physically plausible, and the overall scene conveys mythological gravity through restraint rather than spectacle.
""",
    "ranyiyu" : """
    A realistic ancient mountain-and-water landscape inspired by early Chinese mythology, specifically the description of Yingti Mountain from The Classic of Mountains and Seas (Shan Hai Jing).

The environment depicts a remote, tranquil region shaped by pale stone and flowing water: smooth white cliffs, mineral-rich slopes, and a terrain that feels ancient and stable. Vegetation across the mountains appears unusually light in color, with desaturated foliage and pale bark, reflecting the mythological description that birds and beasts in this region are entirely white. Clear water flows from the mountain, forming a calm river that winds northward into a quiet marshland and wetland basin. The ground near the water is damp and reflective, while higher elevations remain dry, subtly suggesting deposits of gold and jade beneath the surface. The overall color palette is restrained and cool, dominated by ivory white, light gray, pale gold, and muted blue-green tones. Soft, diffused lighting and thin mist create a serene, timeless atmosphere.

At the center foreground of the scene stands a single human figure, shown full body from head to toe, fully visible within the frame. The human figure is of natural, moderate scale relative to the environment, standing firmly on the ground with both feet clearly touching the earth. The person faces toward the camera in a frontal, upright posture, calm and composed, as if quietly observing the landscape. No other human figures appear in the scene.

Behind the human figure, positioned slightly to the rear and rising from above the water and marshland, appears a mythological creature described in Shan Hai Jing: the Ran-yi Fish (冉遗鱼). The creature possesses a fish-like main body but must not resemble any real-world fish species. Its anatomy is clearly non-biological by modern standards. Emerging from its body are six clearly visible, jointed limbs, arranged in a structurally impossible configuration that cannot be mistaken for fins or natural appendages. These limbs are fully formed, solid, and unmistakable, giving the creature an ancient and unnatural presence.

The head of the creature is serpent-like yet unfamiliar, with proportions and structure that do not align with any known animal. Its form feels ancient and unsettling rather than aggressive, as if governed by unknown physical rules. The creature is significantly larger than the human figure, its scale altering the spatial balance of the scene and making its presence impossible to ignore. It hovers or rises gently above the water, not attacking, not retreating, but existing as a watchful and abnormal entity within the landscape.

The composition emphasizes spatial clarity and realism: the grounded human figure in the foreground, the expansive mountain-and-water environment, and the mythic creature occupying the mid-to-background space with clear physical volume. The visual style should be cinematic and realistic, avoiding cartoon, anime, or exaggerated fantasy illustration styles. Lighting remains consistent and natural, textures are physically plausible, and the scene conveys mythological significance through restraint and calmness, while preserving a clear sense of anatomical abnormality and otherness in the creature.

""",
    "bibi" : """
    A realistic ancient mountain scene grounded in early Chinese mythology, specifically inspired by the description of Gufeng Mountain from The Classic of Mountains and Seas (Shan Hai Jing).

The environment depicts a harsh and barren mountain region: exposed rock faces, fractured stone ground, and steep slopes devoid of any vegetation. No grass, trees, or plants appear anywhere in the landscape. The mountain surface reveals pale stone interwoven with mineral veins, subtly suggesting the presence of gold and jade beneath the rock. The terrain feels dry and exhausted, shaped by long-term heat and the absence of water. The air appears thin and arid, with dust and heat haze softening distant forms. The overall color palette is restrained and desaturated, dominated by off-white stone, light gray rock, and muted sandy-gold tones. Lighting is bright but diffused, as if filtered through a dry, bleached sky, reinforcing the atmosphere of prolonged drought.

In the center of the image stands a single human figure, shown full body from head to toe, clearly visible and fully within the frame. The figure is of moderate, natural size relative to the environment — not tiny, not dominant — standing firmly on the ground with both feet clearly touching the earth. The human faces directly toward the camera in a frontal view, standing still and composed. The posture is calm and restrained, conveying observation rather than fear or action. No other human figures appear anywhere in the scene.

Behind the human, positioned in the right rear area of the scene and hovering low above the rocky ground or perched upon a raised stone formation, is a mythical creature described in Shan Hai Jing:
The Bi-bi (獙獙), a fox-like beast with wings. The creature is integrated naturally into the environment, its form clearly visible yet not exaggerated. It does not attack or confront the human directly, instead remaining still and watchful, its presence acting as an omen rather than an aggressor. The creature’s positioning emphasizes distance and inevitability rather than immediate threat.

The composition emphasizes spatial clarity and narrative restraint: the grounded human figure at the center, the winged beast behind and to the right, and the vast, empty mountain landscape surrounding them. The visual style should be cinematic and realistic, avoiding cartoon, anime, or exaggerated fantasy illustration styles. Lighting remains consistent and physically plausible, textures are natural and grounded, and the scene conveys mythological significance through emptiness, dryness, and stillness rather than overt spectacle.
""",
}

def get_background_prompt(beast_id = 'lei'):
    return BACKGROUND_PROMPTS.get(beast_id, BACKGROUND_PROMPTS['lei'])